/*THIS IS THE DEPARTMENT TABLE, FOR EXAMPLE ROBOTICS DEPARTMENT*/
CREATE TABLE  department(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE ,
    tagline VARCHAR(255),
    description TEXT
);

/*THIS IS THE TEAM TABLE, FOR EXAMPLE WHAT TEAMS EXISTS UNDER A CERTAIN DEPARTMENT */
CREATE TABLE team(
    id BIGSERIAL PRIMARY KEY ,
    department_id BIGINT NOT NULL REFERENCES department(id),
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL UNIQUE
);

/*THIS IS THE JOB POSTINGS DB THAT DETAILS A SPECIFIC JOB ROLE */
CREATE TABLE job_posting(
    id BIGSERIAL PRIMARY KEY,
    /*EVERY JOB POSTING BELONGS TO ONE DEPARTMENT*/
    team_id BIGINT NOT NULL REFERENCES team(id),
    title VARCHAR(150) NOT NULL,
    location VARCHAR(150),
    /*FULL TIME - INTERN - PART TIME - SEASONAL */
    job_type VARCHAR(30) NOT NULL,
    is_remote BOOLEAN NOT NULL DEFAULT FALSE,
    req_id VARCHAR(50) UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    posted_at TIMESTAMP NOT NULL DEFAULT now(),
    about_role TEXT,
    responsibilities TEXT,
    requirements TEXT,
    bonus_qualifications TEXT,
    salary_min INTEGER,
    salary_max INTEGER
);
